# Generated by Django 3.2.25 on 2024-10-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='result',
            field=models.TextField(default=''),
        ),
    ]
