# Generated by Django 3.2.25 on 2024-10-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241005_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='code',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
